const music = [
  "Lord Huron - The Night We Met",
  "The Lumineers - Ho Hey",
  "The Lumineers - Cleopatra",
  "The Lumineers - Ophelia",
  "The Lumineers - Sleep on the Floor",
  "The Lumineers - Flowers in Your Hair",
  "The Lumineers - Leave Me Alone",
  "The Lumineers - Sleep on the Floor",
  "The Lumineers - Flowers in Your Hair",
  "The Lumineers - Leave Me Alone",
  "Cigarettes After Sex - K. (I'm So in Love with You)",
  "Cigarettes After Sex - Always",
  "Cigarettes After Sex - Apocalypse",
  "Cigarettes After Sex - Heaven",
  "Cigarettes After Sex - The Body",
  "Cigarettes After Sex - The Fall",
]
